# MetaGen Brain: Model Training & Fine-Tuning Suite

This notebook contains the foundational fine-tuning pipeline for the Mistral 7B Instruct YouTube SEO model.

### Lightweight Small Language Models (SLMs) for Sub-10s CPU Fallback:
For high-speed CPU deployment (under 10s inference latency on 2 vCPUs), train our specialized SLMs:
- **Qwen 2.5 1.5B Instruct:** notebooks/YT_Model_Brain_Qwen2.5_1.5B.ipynb (Native ChatML, ~1.05 GB GGUF, ~35 tok/s CPU)
- **Llama 3.2 1B Instruct:** notebooks/YT_Model_Brain_Llama3.2_1B.ipynb (Llama 3 formatting, ~750 MB GGUF, ~40 tok/s CPU)

### Full-Scale 7B/8B Parameter Models:
- **Qwen 2.5 7B Instruct:** notebooks/YT_Model_Brain_Qwen.ipynb
- **Llama 3.1 8B Instruct:** notebooks/YT_Model_Brain_Llama3.ipynb
- **Phi-4 Mini 3.8B:** notebooks/YT_Model_Brain_Phi4.ipynb

In [ ]:
!pip install -q -U transformers peft trl datasets bitsandbytes accelerate

In [ ]:
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
import gc

In [ ]:
# Load your newly created dataset
dataset = load_dataset("json", data_files="youtube_finetuning_dataset.json", split="train")

def format_prompts(examples):
    """Formats the JSON into a single string for the model to read."""
    texts = []
    for instruction, input_text, output in zip(examples['instruction'], examples['input'], examples['output']):
        # Create the prompt template
        text = f"<s>[INST] {instruction}\n{input_text} [/INST] {output}</s>"
        texts.append(text)
    return {"text": texts}

dataset = dataset.map(format_prompts, batched=True)

In [ ]:
# 1. Force clear any residual memory
torch.cuda.empty_cache()
gc.collect()

# 2. Configure 4-bit Quantization
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

# 3. Load the Base Model and Tokenizer
model_id = "mistralai/Mistral-7B-Instruct-v0.2"
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

print("Downloading and loading model weights to GPU...")
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map={"": 0},
    torch_dtype=torch.float16
)

print("Preparing model for training...")
model = prepare_model_for_kbit_training(model)

# 4. Configure LoRA
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)

# -----------------------------------------------------------------
# THE ULTIMATE BFLOAT16 PURGE
# -----------------------------------------------------------------
print("Hunting down and converting lingering BFloat16 weights...")
for name, param in model.named_parameters():
    if param.dtype == torch.bfloat16:
        param.data = param.data.to(torch.float16)

# Force the internal config so the Trainer doesn't get confused
model.config.torch_dtype = torch.float16

print("✅ Model loaded and completely purged of BFloat16!")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
`torch_dtype` is deprecated! Use `dtype` instead!

Downloading and loading model weights to GPU...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Preparing model for training...
Hunting down and converting lingering BFloat16 weights...
✅ Model loaded and completely purged of BFloat16!

In [ ]:
# 5. Set up the Trainer (UPDATED for the latest trl library)
training_args = SFTConfig(
    output_dir="./yt_lora_results",
    dataset_text_field="text",
    max_length=512,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_steps=10,
    max_steps=150,
    optim="paged_adamw_8bit",
    fp16=True,
)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    args=training_args,
)

In [ ]:
# 6. START TRAINING!
# a. Force all trainable parameters (LoRA weights) to standard Float32
# This bypasses the T4 hardware crash and stabilizes the training loss
for param in trainer.model.parameters():
    if param.requires_grad:
        param.data = param.data.to(torch.float32)

# b. Double-check and forcefully eliminate any deep-nested BFloat16 tensors
for name, param in trainer.model.named_parameters():
    if param.dtype == torch.bfloat16:
        param.data = param.data.to(torch.float16)

# c. Explicitly hardcode the trainer's precision settings just before execution
trainer.args.bf16 = False
trainer.args.fp16 = True

# d. START TRAINING!
print("Starting the fine-tuning process...")
trainer.train()

Starting the fine-tuning process...

TrainOutput(global_step=150, training_loss=1.2415373229980469, metrics={'train_runtime': 1692.9712, 'train_samples_per_second': 0.709, 'train_steps_per_second': 0.089, 'total_flos': 2.368789905363763e+16, 'train_loss': 1.2415373229980469})

In [ ]:
# 7. Save your custom weights
trainer.model.save_pretrained("yt-custom-lora-adapter")
print("Training complete! Custom weights saved.")

Training complete! Custom weights saved.

In [ ]:
import torch

# 1. Define a brand new topic to test
test_instruction = "You are an expert YouTube SEO strategist. Generate a viral title, description, and tags for this topic."
test_input = "Topic: How to build a modern portfolio website. Context: In this video, I will show you step by step how to build a stunning, responsive portfolio website using React, Tailwind CSS, and Neo-Brutalism design concepts to help you land your first tech job."

# 2. Format it exactly how the model was trained
prompt = f"<s>[INST] {test_instruction}\n{test_input} [/INST]"

# 3. Tokenize and move to GPU
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

# 4. Generate the response
print("Generating AI response...\n")
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=250,
        temperature=0.7,      # Add a little creativity
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )

# 5. Decode and print!
result = tokenizer.decode(outputs[0], skip_special_tokens=True)
# Only print the output part (hide the prompt)
print(result.split("[/INST]")[-1].strip())

`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
Caching is incompatible with gradient checkpointing in MistralDecoderLayer. Setting `past_key_values=None`.

Generating AI response...

{" " +  Question: Q Q Q #[[[1[INSTED: Question: Question  Question: Q Q #[[INST_ Question: Q #[INST_ Question: Question  Q #  Question: Question: Q # -  # @
 Q Q #2** ( Question: Question: Question Question: Question: Question: Q Q #  Question: Question: Question: Question: Question: Question Question: Question: Question: Question: Q #  Question: Question: Question  Q Q Q Q #[[INST: Question  Question: Question: Question Question: Question: Question: Question  Question: Question: Question: Question  Q # [ + i #  Question: Question: Question Question  Question: Question: Question: Question: Question: Question: Question: Question Question: Question: Question  Question  Question: Question Question: Question: Question: Question: Question: Q Q #  Question: Question: Question: Question: Question: Question: # []
 Q # #[] ( Question: Question: Question: Question  Question: Question: Question: Question: Q # |  Q #  Q #  Question: Question: #[[[INST IN

In [ ]:
import shutil
from google.colab import files

# Zip the folder
print("Zipping the adapter...")
shutil.make_archive("yt-custom-lora-adapter", 'zip', "yt-custom-lora-adapter")

# Download it to your computer
print("Downloading...")
files.download("yt-custom-lora-adapter.zip")

Zipping the adapter...
Downloading...

In [ ]:
import shutil
from google.colab import files

# Zip the folder
print("Zipping the adapter...")
shutil.make_archive("yt_lora_results", 'zip', "yt_lora_results")

# Download it to your computer
print("Downloading...")
files.download("yt_lora_results.zip")

Zipping the adapter...
Downloading...

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

# 1. Clean Configuration
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16
)

model_id = "mistralai/Mistral-7B-Instruct-v0.2"
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

print("Loading clean base model...")
base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16
)

print("Injecting your custom LoRA brain...")
# 2. Attach the adapter you just trained!
model = PeftModel.from_pretrained(base_model, "yt-custom-lora-adapter")

# 3. CRITICAL: Put the model in evaluation (inference) mode!
model.eval()
base_model.config.use_cache = True

# 4. Prepare the Test Prompt
test_instruction = "You are an expert YouTube SEO strategist. Generate a viral title, description, and tags for this topic."
test_input = "Topic: How to build a modern portfolio website. Context: In this video, I will show you step by step how to build a stunning, responsive portfolio website using React, Tailwind CSS, and Neo-Brutalism design concepts to help you land your first tech job."

prompt = f"<s>[INST] {test_instruction}\n{test_input} [/INST]"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

# 5. Generate the Output
print("\nGenerating AI response...\n")
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=250,
        temperature=0.7,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )

# 6. Decode and display the magic
result = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("--- FINAL OUTPUT ---")
print(result.split("[/INST]")[-1].strip())

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
`torch_dtype` is deprecated! Use `dtype` instead!

Loading clean base model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Injecting your custom LoRA brain...

Generating AI response...

--- FINAL OUTPUT ---
{"title": "How to build a modern portfolio website", "description": "In this video, I will show you step by step how to build a stunning, responsive portfolio website using React, Tailwind CSS, and Neo-Brutalism design concepts to help you land your first tech job. \n\n\ud83d\udd34\ufe0f Full course: https://bit.ly/3EG2xXk\n\n\u2705\ufe0f Learn more about us:\n\ud83d\udc49\u200d\u1f46\u00a0MyCodingJourney\u200d\u1f46\ud83d\udc49\u00a0https://www.youtube.com/c/MyCodingJourney\n\n\u2705\ufe0f Learn more about our sponsors:\n\ud83d\udc49\u200d\u1f46\u00a0Solo

In [ ]:
from huggingface_hub import login

# 1. Log in to Hugging Face
login("YOUR_HF_TOKEN")

# 2. Push your custom LoRA adapter to your profile!
# Replace 'your-username' with your actual Hugging Face username
hf_username = "SujalChhajed925"
repo_name = f"{hf_username}/yt-seo-mistral-lora"

print(f"Uploading custom model to {repo_name}...")
model.push_to_hub(repo_name)
tokenizer.push_to_hub(repo_name)

print("✅ Upload complete! Your custom model is now live on Hugging Face!")

Uploading custom model to SujalChhajed925/yt-seo-mistral-lora...

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   1%|1         |  557kB / 54.6MB

README.md: 0.00B [00:00, ?B/s]

✅ Upload complete! Your custom model is now live on Hugging Face!

In [ ]:
!pip install -q -U accelerate peft transformers

In [ ]:
import torch
import gc
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
from huggingface_hub import login

# 1. Log in to Hugging Face
login("YOUR_HF_TOKEN") # <-- IMPORTANT: Put your actual token here!

# 2. Wipe the GPU completely clean
torch.cuda.empty_cache()
gc.collect()

print("Loading base model strictly into the 15GB GPU VRAM...")
base_model_id = "mistralai/Mistral-7B-Instruct-v0.2"

# 3. We load directly to GPU 0. No CPU, no Disk offloading.
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map={"": 0}
)

# -----------------------------------------------------------------
# 🚨 BUG FIX FOR "UNHASHABLE TYPE: SET"
# This prevents Peft from crashing when we don't use disk offloading
if hasattr(base_model, "_no_split_modules"):
    base_model._no_split_modules = ["MistralDecoderLayer"]
if hasattr(base_model.config, "no_split_module_classes"):
    base_model.config.no_split_module_classes = ["MistralDecoderLayer"]
# -----------------------------------------------------------------

tokenizer = AutoTokenizer.from_pretrained(base_model_id)

print("Loading custom LoRA adapter...")
model = PeftModel.from_pretrained(base_model, "yt-custom-lora-adapter")

print("Merging weights... (Doing this in-place on the GPU)")
# The LoRA weights are small (~50MB), so this should just squeeze into the remaining VRAM!
model = model.merge_and_unload()

hf_username = "SujalChhajed925"
repo_name = f"{hf_username}/yt-seo-mistral-merged"

print(f"Uploading standalone model to {repo_name}...")
model.push_to_hub(repo_name, max_shard_size="2GB")
tokenizer.push_to_hub(repo_name)

print("✅ Merging and Upload complete! Your standalone model is ready for production.")

Loading base model strictly into the 15GB GPU VRAM...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Loading custom LoRA adapter...
Merging weights... (Doing this in-place on the GPU)
Uploading standalone model to SujalChhajed925/yt-seo-mistral-merged...

Writing model shards:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...0003-of-00008.safetensors:   0%|          | 8.28MB / 1.94GB

  ...0001-of-00008.safetensors:   1%|          | 16.8MB / 1.95GB

  ...0002-of-00008.safetensors:   1%|1         | 25.1MB / 1.99GB

  ...0006-of-00008.safetensors:   1%|          | 16.7MB / 1.99GB

  ...0008-of-00008.safetensors:   2%|2         | 16.8MB /  755MB

  ...0004-of-00008.safetensors:   0%|          | 8.31MB / 1.99GB

  ...0007-of-00008.safetensors:   0%|          | 8.31MB / 1.94GB

  ...0005-of-00008.safetensors:   0%|          | 8.36MB / 1.94GB

README.md: 0.00B [00:00, ?B/s]

✅ Merging and Upload complete! Your standalone model is ready for production.

In [ ]:
# Clone the library and compile it
!git clone https://github.com/ggerganov/llama.cpp
%cd llama.cpp
!make -j
!pip install -r requirements.txt
%cd ..

fatal: destination path 'llama.cpp' already exists and is not an empty directory.
/content/llama.cpp
Makefile:6: *** Build system changed:
 The Makefile build has been replaced by CMake.

 For build instructions see:
 https://github.com/ggml-org/llama.cpp/blob/master/docs/build.md

.  Stop.
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/nightly, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/nightly, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/nightly
Ignoring torch: markers 'platform_machine == "s390x"' don't match your environment
Ignoring torch: markers 'platform_machine == "s390x"' don't match your environment
Requirement already satisfied: numpy~=1.26.4 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 1)) (1.26.4)
Requirement already satisfied: sentencepiece<0.3.0,>=0.1.98 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 2)) (0.2.1)
Collecting transformers<5.0.0,>=4.57.1 (from -r ./requirements/requirements-convert_legacy_llama.txt (line 4))
  Using cached transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: gguf>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 6)) (0.17.1)
Requirement already satisfied: protobuf<5.0.0,>=4.21.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 7)) (4.25.8)
Requirement already satisfied: torch~=2.6.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (2.6.0+cpu)
Requirement already satisfied: aiohttp~=3.9.3 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 1)) (3.9.5)
Requirement already satisfied: pytest~=8.3.3 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 2)) (8.3.5)
Collecting huggingface_hub<1.0,>=0.34.0 (from -r ./requirements/requirements-tool_bench.txt (line 3))
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: matplotlib~=3.10.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 4)) (3.10.0)
Requirement already satisfied: openai~=2.14.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 6)) (2.14.0)
Requirement already satisfied: pandas~=2.2.3 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 7)) (2.2.3)
Requirement already satisfied: prometheus-client~=0.20.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 8)) (0.20.0)
Requirement already satisfied: requests~=2.32.3 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 9)) (2.32.4)
Requirement already satisfied: wget~=3.2 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 10)) (3.2)
Requirement already satisfied: typer~=0.15.1 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 11)) (0.15.4)
Requirement already satisfied: seaborn~=0.13.2 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 12)) (0.13.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.57.1->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (3.20.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.57.1->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.57.1->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.57.1->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.57.1->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.57.1->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.57.1->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (4.67.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch~=2.6.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch~=2.6.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch~=2.6.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch~=2.6.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (2025.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch~=2.6.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch~=2.6.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch~=2.6.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (1.3.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (6.7.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (1.22.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.12/dist-packages (from pytest~=8.3.3->-r ./requirements/requirements-tool_bench.txt (line 2)) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest~=8.3.3->-r ./requirements/requirements-tool_bench.txt (line 2)) (1.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0,>=0.34.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 4)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 4)) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 4)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 4)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 4)) (2.9.0.post0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (1.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.2.3->-r ./requirements/requirements-tool_bench.txt (line 7)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.2.3->-r ./requirements/requirements-tool_bench.txt (line 7)) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests~=2.32.3->-r ./requirements/requirements-tool_bench.txt (line 9)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests~=2.32.3->-r ./requirements/requirements-tool_bench.txt (line 9)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests~=2.32.3->-r ./requirements/requirements-tool_bench.txt (line 9)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests~=2.32.3->-r ./requirements/requirements-tool_bench.txt (line 9)) (2026.1.4)
Requirement already satisfied: click<8.2,>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer~=0.15.1->-r ./requirements/requirements-tool_bench.txt (line 11)) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer~=0.15.1->-r ./requirements/requirements-tool_bench.txt (line 11)) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer~=0.15.1->-r ./requirements/requirements-tool_bench.txt (line 11)) (13.9.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 6)) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 4)) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer~=0.15.1->-r ./requirements/requirements-tool_bench.txt (line 11)) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer~=0.15.1->-r ./requirements/requirements-tool_bench.txt (line 11)) (2.19.2)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.0->aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (0.4.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch~=2.6.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer~=0.15.1->-r ./requirements/requirements-tool_bench.txt (line 11)) (0.1.2)
Using cached transformers-4.57.6-py3-none-any.whl (12.0 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Installing collected packages: huggingface_hub, transformers
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: transformers
    Found existing installation: transformers 5.2.0
    Uninstalling transformers-5.2.0:
      Successfully uninstalled transformers-5.2.0
Successfully installed huggingface_hub-0.36.2 transformers-4.57.6

/content

In [ ]:
!pip install -q -U sentencepiece tokenizers transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 553.3/553.3 kB 18.5 MB/s eta 0:00:00

In [ ]:
import os
import subprocess
import sys
import shutil
from huggingface_hub import snapshot_download, HfApi, hf_hub_download

# 1. Download Model
print("1. Downloading your 14.5GB model from Hugging Face...")
model_path = snapshot_download(repo_id="SujalChhajed925/yt-seo-mistral-merged")

# 1.5 CRITICAL HOTFIX: Inject the missing tokenizer dictionary!
print("\n1.5 Patching missing tokenizer dictionary...")
try:
    original_tokenizer_path = hf_hub_download(repo_id="mistralai/Mistral-7B-Instruct-v0.2", filename="tokenizer.model")
    shutil.copy(original_tokenizer_path, os.path.join(model_path, "tokenizer.model"))
    print("✅ Tokenizer patched successfully!")
except Exception as e:
    print(f"⚠️ Could not patch tokenizer automatically: {e}")

# 2. Convert to uncompressed GGUF
print("\n2. Converting to standard GGUF format... (This takes a couple of minutes)")
convert_cmd = [sys.executable, "llama.cpp/convert_hf_to_gguf.py", model_path, "--outfile", "uncompressed.gguf"]
result_convert = subprocess.run(convert_cmd, capture_output=True, text=True)

if not os.path.exists("uncompressed.gguf"):
    print("❌ CONVERSION FAILED! Here is the hidden error log:")
    print(result_convert.stderr)
    sys.exit(1)
print("✅ Conversion to GGUF complete!")

# 3. Quantize to 4GB
print("\n3. Quantizing (Compressing) down to 4GB... (CPU working hard!)")
quantize_exe = "./llama.cpp/llama-quantize" if os.path.exists("./llama.cpp/llama-quantize") else "./llama.cpp/quantize"
quantize_cmd = [quantize_exe, "uncompressed.gguf", "custom-mistral-yt-seo-Q4_K_M.gguf", "Q4_K_M"]
result_quantize = subprocess.run(quantize_cmd, capture_output=True, text=True)

if not os.path.exists("custom-mistral-yt-seo-Q4_K_M.gguf"):
    print("❌ QUANTIZATION FAILED! Here is the hidden error log:")
    print(result_quantize.stderr)
    sys.exit(1)
print("✅ Compression down to 4GB complete!")

# 4. Upload
print("\n4. Uploading your optimized 4GB model to your profile...")
api = HfApi()
try:
    api.upload_file(
        path_or_fileobj="custom-mistral-yt-seo-Q4_K_M.gguf",
        path_in_repo="custom-mistral-yt-seo-Q4_K_M.gguf",
        repo_id="SujalChhajed925/yt-seo-mistral-merged",
        token="YOUR_HF_TOKEN" # <-- IMPORTANT: Put your token here!
    )
    print("\n✅ Upload complete! You can close Colab forever.")
except Exception as e:
    print(f"\n❌ UPLOAD FAILED: {str(e)}")

1. Downloading your 14.5GB model from Hugging Face...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 16 files:   0%|          | 0/16 [00:00<?, ?it/s]

1.5 Patching missing tokenizer dictionary...
✅ Tokenizer patched successfully!

2. Converting to standard GGUF format... (This takes a couple of minutes)
✅ Conversion to GGUF complete!

3. Quantizing (Compressing) down to 4GB... (CPU working hard!)

FileNotFoundError: [Errno 2] No such file or directory: './llama.cpp/quantize'

In [1]:
import os
import subprocess
import sys
import shutil

# --- STEP 0: Rebuild the C++ Engine ---
print("0. Setting up the C++ engine (Fixing the FileNotFoundError)...")
if not os.path.exists("llama.cpp"):
    os.system("git clone https://github.com/ggerganov/llama.cpp")
    os.system("cd llama.cpp && make -j")
os.system(f"{sys.executable} -m pip install -q -U sentencepiece tokenizers transformers huggingface_hub")

from huggingface_hub import snapshot_download, HfApi, hf_hub_download

# --- STEP 1: Download Model ---
print("\n1. Downloading your 14.5GB model from Hugging Face...")
model_path = snapshot_download(repo_id="SujalChhajed925/yt-seo-mistral-merged")

# --- STEP 1.5: Patch Tokenizer ---
print("\n1.5 Patching missing tokenizer dictionary...")
try:
    original_tokenizer_path = hf_hub_download(repo_id="mistralai/Mistral-7B-Instruct-v0.2", filename="tokenizer.model")
    shutil.copy(original_tokenizer_path, os.path.join(model_path, "tokenizer.model"))
    print("✅ Tokenizer patched successfully!")
except Exception as e:
    print(f"⚠️ Could not patch tokenizer automatically: {e}")

# --- STEP 2: Convert to GGUF ---
print("\n2. Converting to standard GGUF format...")
convert_cmd = [sys.executable, "llama.cpp/convert_hf_to_gguf.py", model_path, "--outfile", "uncompressed.gguf"]
result_convert = subprocess.run(convert_cmd, capture_output=True, text=True)

if not os.path.exists("uncompressed.gguf"):
    print("❌ CONVERSION FAILED! Here is the hidden error log:")
    print(result_convert.stderr)
    sys.exit(1)
print("✅ Conversion to GGUF complete!")

# --- STEP 3: Quantize ---
print("\n3. Quantizing (Compressing) down to 4GB... (CPU working hard!)")
quantize_exe = "./llama.cpp/llama-quantize" if os.path.exists("./llama.cpp/llama-quantize") else "./llama.cpp/quantize"
quantize_cmd = [quantize_exe, "uncompressed.gguf", "custom-mistral-yt-seo-Q4_K_M.gguf", "Q4_K_M"]
result_quantize = subprocess.run(quantize_cmd, capture_output=True, text=True)

if not os.path.exists("custom-mistral-yt-seo-Q4_K_M.gguf"):
    print("❌ QUANTIZATION FAILED! Here is the hidden error log:")
    print(result_quantize.stderr)
    sys.exit(1)
print("✅ Compression down to 4GB complete!")

# --- STEP 4: Upload ---
print("\n4. Uploading your optimized 4GB model to your profile...")
api = HfApi()
try:
    api.upload_file(
        path_or_fileobj="custom-mistral-yt-seo-Q4_K_M.gguf",
        path_in_repo="custom-mistral-yt-seo-Q4_K_M.gguf",
        repo_id="SujalChhajed925/yt-seo-mistral-merged",
        token="YOUR_HF_TOKEN" # <-- IMPORTANT: Put your token here!
    )
    print("\n✅ Upload complete! You can close Colab forever.")
except Exception as e:
    print(f"\n❌ UPLOAD FAILED: {str(e)}")

0. Setting up the C++ engine (Fixing the FileNotFoundError)...

1. Downloading your 14.5GB model from Hugging Face...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 16 files:   0%|          | 0/16 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

1.5 Patching missing tokenizer dictionary...

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

✅ Tokenizer patched successfully!

2. Converting to standard GGUF format...
✅ Conversion to GGUF complete!

3. Quantizing (Compressing) down to 4GB... (CPU working hard!)

FileNotFoundError: [Errno 2] No such file or directory: './llama.cpp/quantize'

In [2]:
# Force start in the root directory
%cd /content

# Clean up and get fresh code
!rm -rf llama.cpp
!git clone https://github.com/ggerganov/llama.cpp

# Move inside and compile with live logs
%cd llama.cpp
!cmake -B build
!cmake --build build --config Release -j 2

/content
Cloning into 'llama.cpp'...
remote: Enumerating objects: 80438, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 80438 (delta 35), reused 26 (delta 26), pack-reused 80376 (from 3)
Receiving objects: 100% (80438/80438), 296.57 MiB | 24.67 MiB/s, done.
Resolving deltas: 100% (58131/58131), done.
/content/llama.cpp
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.34.1")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- ggml version: 0.9.7
-- ggml commit:  afa6bfe4f
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.2")
-- Performing Test OPENSSL_VERSION_SUPPORTED
-- Performing Test OPENSSL_VERSION_SUPPORTED - Success
-- OpenSSL found: 3.0.2
-- Generating embedded license file for target: common
-- Configuring done (1.8s)
-- Generating done (0.3s)
-- Build files have been written to: /content/llama.cpp/build
[  0%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  0%] Building CXX object common/CMakeFiles/build_info.dir/build-info.cpp.o
[  0%] Built target build_info
[  0%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml.cpp.o
[  0%] Building CXX object vendor/cpp-httplib/CMakeFiles/cpp-httplib.dir/httplib.cpp.o
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  2%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
[  2%] Linking CXX shared library ../../bin/libggml-base.so
[  2%] Built target ggml-base
[  3%] Building C object examples/gguf-hash/CMakeFiles/sha256.dir/deps/sha256/sha256.c.o
[  3%] Built target sha256
[  4%] Building C object examples/gguf-hash/CMakeFiles/xxhash.dir/deps/xxhash/xxhash.c.o
[  4%] Built target xxhash
[  4%] Building C object examples/gguf-hash/CMakeFiles/sha1.dir/deps/sha1/sha1.c.o
[  4%] Built target sha1
[  4%] Building CXX object tools/mtmd/CMakeFiles/llama-llava-cli.dir/deprecation-warning.cpp.o
[  4%] Linking CXX executable ../../bin/llama-llava-cli
[  4%] Built target llama-llava-cli
[  5%] Building CXX object tools/mtmd/CMakeFiles/llama-gemma3-cli.dir/deprecation-warning.cpp.o
[  5%] Linking CXX executable ../../bin/llama-gemma3-cli
[  5%] Built target llama-gemma3-cli
[  6%] Building CXX object tools/mtmd/CMakeFiles/llama-minicpmv-cli.dir/deprecation-warning.cpp.o
[  6%] Linking CXX executable ../../bin/llama-minicpmv-cli
[  6%] Built target llama-minicpmv-cli
[  6%] Building CXX object tools/mtmd/CMakeFiles/llama-qwen2vl-cli.dir/deprecation-warning.cpp.o
[  6%] Linking CXX executable ../../bin/llama-qwen2vl-cli
[  6%] Built target llama-qwen2vl-cli
[  6%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.c.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/repack.cpp.o
[  7%] Linking CXX static library libcpp-httplib.a
[  7%] Built target cpp-httplib
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/hbm.cpp.o
[  7%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/quants.c.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/traits.cpp.o
[  8%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/amx.cpp.o
[  8%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/mmq.cpp.o
[  8%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/binary-ops.cpp.o
[  8%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/unary-ops.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/vec.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ops.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/llamafile/sgemm.cpp.o
[  9%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/quants.c.o
[ 10%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/repack.cpp.o
[ 10%] Linking CXX shared library ../../bin/libggml-cpu.so
[ 10%] Built target ggml-cpu
[ 10%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-dl.cpp.o
[ 11%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-reg.cpp.o
[ 11%] Linking CXX shared library ../../bin/libggml.so
[ 11%] Built target ggml
[ 11%] Building CXX object examples/gguf-hash/CMakeFiles/llama-gguf-hash.dir/gguf-hash.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama.cpp.o
[ 11%] Linking CXX executable ../../bin/llama-gguf-hash
[ 11%] Built target llama-gguf-hash
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-adapter.cpp.o
[ 11%] Building CXX object examples/gguf/CMakeFiles/llama-gguf.dir/gguf.cpp.o
[ 12%] Linking CXX executable ../../bin/llama-gguf
[ 12%] Built target llama-gguf
[ 12%] Building CXX object src/CMakeFiles/llama.dir/llama-arch.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-batch.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-chat.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-context.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-cparams.cpp.o
[ 14%] Building CXX object src/CMakeFiles/llama.dir/llama-grammar.cpp.o
[ 14%] Building CXX object src/CMakeFiles/llama.dir/llama-graph.cpp.o
[ 14%] Building CXX object src/CMakeFiles/llama.dir/llama-hparams.cpp.o
[ 14%] Building CXX object src/CMakeFiles/llama.dir/llama-impl.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-io.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache-iswa.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-memory.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-hybrid.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-hybrid-iswa.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-recurrent.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-mmap.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-model-loader.cpp.o
[ 17%] Building CXX object src/CMakeFiles/llama.dir/llama-model-saver.cpp.o
[ 17%] Building CXX object src/CMakeFiles/llama.dir/llama-model.cpp.o
[ 17%] Building CXX object src/CMakeFiles/llama.dir/llama-quant.cpp.o
[ 17%] Building CXX object src/CMakeFiles/llama.dir/llama-sampler.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-vocab.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/unicode-data.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/unicode.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/models/afmoe.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/apertus.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/arcee.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/arctic.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/arwkv7.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/baichuan.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/bailingmoe.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/bailingmoe2.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/bert.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/bitnet.cpp.o
[ 21%] Building CXX object src/CMakeFiles/llama.dir/models/bloom.cpp.o
[ 21%] Building CXX object src/CMakeFiles/llama.dir/models/chameleon.cpp.o
[ 21%] Building CXX object src/CMakeFiles/llama.dir/models/chatglm.cpp.o
[ 21%] Building CXX object src/CMakeFiles/llama.dir/models/codeshell.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/cogvlm.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/cohere2-iswa.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/command-r.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/dbrx.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/deci.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek2.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/delta-net-base.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/dots1.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/dream.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/ernie4-5-moe.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/ernie4-5.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/exaone-moe.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/exaone.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/exaone4.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/falcon-h1.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/falcon.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/gemma-embedding.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/gemma.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/gemma2-iswa.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/gemma3.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/gemma3n-iswa.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/glm4-moe.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/glm4.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/gpt2.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/gptneox.cpp.o
[ 28%] Building CXX object src/CMakeFiles/llama.dir/models/granite-hybrid.cpp.o
[ 28%] Building CXX object src/CMakeFiles/llama.dir/models/granite.cpp.o
[ 28%] Building CXX object src/CMakeFiles/llama.dir/models/grok.cpp.o
[ 28%] Building CXX object src/CMakeFiles/llama.dir/models/grovemoe.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-dense.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-moe.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/internlm2.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/jais.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/jamba.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/kimi-linear.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/lfm2.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/llada-moe.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/llada.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/llama-iswa.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/llama.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/maincoder.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/mamba-base.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/mamba.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/mimo2-iswa.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/minicpm3.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/minimax-m2.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/mistral3.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/modern-bert.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/mpt.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron-h.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/neo-bert.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/olmo.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/olmo2.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/olmoe.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/openai-moe-iswa.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/openelm.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/orion.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/pangu-embedded.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/phi2.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/phi3.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/plamo.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/plamo2.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/plamo3.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/plm.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/qwen.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2moe.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2vl.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/qwen35.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/qwen35moe.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3moe.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3next.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3vl-moe.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3vl.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/refact.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/rnd1.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6-base.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6qwen2.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv7-base.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv7.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/seed-oss.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/smallthinker.cpp.o
[ 42%] Building CXX object src/CMakeFiles/llama.dir/models/smollm3.cpp.o
[ 42%] Building CXX object src/CMakeFiles/llama.dir/models/stablelm.cpp.o
[ 42%] Building CXX object src/CMakeFiles/llama.dir/models/starcoder.cpp.o
[ 42%] Building CXX object src/CMakeFiles/llama.dir/models/starcoder2.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/step35-iswa.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/t5-dec.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/t5-enc.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/wavtokenizer-dec.cpp.o
[ 44%] Building CXX object src/CMakeFiles/llama.dir/models/xverse.cpp.o
[ 44%] Linking CXX shared library ../bin/libllama.so
[ 44%] Built target llama
[ 44%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd.cpp.o
[ 44%] Building CXX object common/CMakeFiles/common.dir/arg.cpp.o
[ 44%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd-audio.cpp.o
[ 44%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd-helper.cpp.o
[ 44%] Building CXX object common/CMakeFiles/common.dir/chat-parser.cpp.o
[ 45%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/clip.cpp.o
[ 45%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/cogvlm.cpp.o
[ 45%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/conformer.cpp.o
[ 45%] Building CXX object common/CMakeFiles/common.dir/chat-parser-xml-toolcall.cpp.o
[ 45%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/glm4v.cpp.o
[ 46%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/internvl.cpp.o
[ 46%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/kimivl.cpp.o
[ 46%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/kimik25.cpp.o
[ 46%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/nemotron-v2-vl.cpp.o
[ 47%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/llama4.cpp.o
[ 47%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/llava.cpp.o
[ 47%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/minicpmv.cpp.o
[ 47%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/pixtral.cpp.o
[ 47%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/qwen2vl.cpp.o
[ 48%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/qwen3vl.cpp.o
[ 48%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/siglip.cpp.o
[ 49%] Building CXX object common/CMakeFiles/common.dir/chat-peg-parser.cpp.o
[ 49%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/whisper-enc.cpp.o
[ 49%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/mobilenetv5.cpp.o
[ 50%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/youtuvl.cpp.o
[ 50%] Building CXX object common/CMakeFiles/common.dir/chat.cpp.o
[ 50%] Linking CXX shared library ../../bin/libmtmd.so
[ 50%] Built target mtmd
[ 50%] Building CXX object common/CMakeFiles/common.dir/common.cpp.o
[ 50%] Building C object tests/CMakeFiles/test-c.dir/test-c.c.o
[ 50%] Linking C executable ../bin/test-c
[ 50%] Built target test-c
[ 51%] Building CXX object examples/simple/CMakeFiles/llama-simple.dir/simple.cpp.o
[ 51%] Linking CXX executable ../../bin/llama-simple
[ 51%] Built target llama-simple
[ 51%] Building CXX object common/CMakeFiles/common.dir/console.cpp.o
[ 51%] Building CXX object examples/simple-chat/CMakeFiles/llama-simple-chat.dir/simple-chat.cpp.o
[ 51%] Linking CXX executable ../../bin/llama-simple-chat
[ 51%] Built target llama-simple-chat
[ 52%] Building CXX object common/CMakeFiles/common.dir/debug.cpp.o
[ 52%] Building CXX object common/CMakeFiles/common.dir/download.cpp.o
[ 52%] Building CXX object common/CMakeFiles/common.dir/json-partial.cpp.o
[ 52%] Building CXX object common/CMakeFiles/common.dir/json-schema-to-grammar.cpp.o
[ 53%] Building CXX object common/CMakeFiles/common.dir/llguidance.cpp.o
[ 53%] Building CXX object common/CMakeFiles/common.dir/log.cpp.o
[ 53%] Building CXX object common/CMakeFiles/common.dir/ngram-cache.cpp.o
[ 53%] Building CXX object common/CMakeFiles/common.dir/ngram-map.cpp.o
[ 53%] Building CXX object common/CMakeFiles/common.dir/ngram-mod.cpp.o
[ 54%] Building CXX object common/CMakeFiles/common.dir/peg-parser.cpp.o
[ 54%] Building CXX object common/CMakeFiles/common.dir/preset.cpp.o
[ 54%] Building CXX object common/CMakeFiles/common.dir/regex-partial.cpp.o
[ 54%] Building CXX object common/CMakeFiles/common.dir/sampling.cpp.o
[ 55%] Building CXX object common/CMakeFiles/common.dir/speculative.cpp.o
[ 55%] Building CXX object common/CMakeFiles/common.dir/unicode.cpp.o
[ 55%] Building CXX object common/CMakeFiles/common.dir/jinja/lexer.cpp.o

In [3]:
# Go back to the root folder where your uncompressed.gguf is sitting
%cd /content

# Run the compression! (Using the standard CMake output path)
!./llama.cpp/build/bin/llama-quantize uncompressed.gguf custom-mistral-yt-seo-Q4_K_M.gguf Q4_K_M || ./llama.cpp/build/llama-quantize uncompressed.gguf custom-mistral-yt-seo-Q4_K_M.gguf Q4_K_M

/content
main: build = 8084 (afa6bfe4f)
main: built with GNU 11.4.0 for Linux x86_64
main: quantizing 'uncompressed.gguf' to 'custom-mistral-yt-seo-Q4_K_M.gguf' as Q4_K_M
llama_model_loader: loaded meta data with 31 key-value pairs and 291 tensors from uncompressed.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = 23f5b32646f768cc5fd1d39aeb28bd9f074c268c
llama_model_loader: - kv   3:                           general.finetune str              = 23f5b32646f768cc5fd1d39aeb28bd9f074c268c
llama_model_loader: - kv   4:                         general.size_label str              = 7.2B
llama_model_loader: - kv   5:                          llama.block_count u32              = 32
llama_model_loader: - kv   6:                       llama.context_length u32              = 32768
llama_model_loader: - kv   7:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   8:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   9:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv  10:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  11:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  12:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  13:                 llama.attention.key_length u32              = 128
llama_model_loader: - kv  14:               llama.attention.value_length u32              = 128
llama_model_loader: - kv  15:                          general.file_type u32              = 1
llama_model_loader: - kv  16:                           llama.vocab_size u32              = 32000
llama_model_loader: - kv  17:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - kv  19:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  20:                         tokenizer.ggml.pre str              = default
llama_model_loader: - kv  21:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  22:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  23:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  24:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  25:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  26:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  27:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  28:               tokenizer.ggml.add_sep_token bool             = false
llama_model_loader: - kv  29:                    tokenizer.chat_template str              = {%- if messages[0]['role'] == 'system...
llama_model_loader: - kv  30:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:  226 tensors
[   1/ 291]                        output.weight - [ 4096, 32000,     1,     1], type =    f16, converting to q6_K .. size =   250.00 MiB ->   102.54 MiB
[   2/ 291]                   output_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[   3/ 291]                    token_embd.weight - [ 4096, 32000,     1,     1], type =    f16, converting to q4_K .. size =   250.00 MiB ->    70.31 MiB
[   4/ 291]                  blk.0.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[   5/ 291]               blk.0.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[   6/ 291]             blk.0.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[   7/ 291]                  blk.0.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[   8/ 291]                  blk.0.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q6_K .. size =     8.00 MiB ->     3.28 MiB
[   9/ 291]                blk.0.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q6_K .. size =   112.00 MiB ->    45.94 MiB
[  10/ 291]                blk.0.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  11/ 291]                blk.0.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  12/ 291]                  blk.0.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  13/ 291]                  blk.1.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  14/ 291]               blk.1.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  15/ 291]             blk.1.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  16/ 291]                  blk.1.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  17/ 291]                  blk.1.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q6_K .. size =     8.00 MiB ->     3.28 MiB
[  18/ 291]                blk.1.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q6_K .. size =   112.00 MiB ->    45.94 MiB
[  19/ 291]                blk.1.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  20/ 291]                blk.1.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  21/ 291]                  blk.1.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  22/ 291]                  blk.2.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  23/ 291]               blk.2.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  24/ 291]             blk.2.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  25/ 291]                  blk.2.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  26/ 291]                  blk.2.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q6_K .. size =     8.00 MiB ->     3.28 MiB
[  27/ 291]                blk.2.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q6_K .. size =   112.00 MiB ->    45.94 MiB
[  28/ 291]                blk.2.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  29/ 291]                blk.2.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  30/ 291]                  blk.2.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  31/ 291]                  blk.3.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  32/ 291]               blk.3.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  33/ 291]             blk.3.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  34/ 291]                  blk.3.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  35/ 291]                  blk.3.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q6_K .. size =     8.00 MiB ->     3.28 MiB
[  36/ 291]                blk.3.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q6_K .. size =   112.00 MiB ->    45.94 MiB
[  37/ 291]                blk.3.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  38/ 291]                blk.3.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  39/ 291]                  blk.3.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  40/ 291]                  blk.4.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  41/ 291]               blk.4.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  42/ 291]             blk.4.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  43/ 291]                  blk.4.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  44/ 291]                  blk.4.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  45/ 291]                blk.4.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  46/ 291]                blk.4.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  47/ 291]                blk.4.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  48/ 291]                  blk.4.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  49/ 291]                  blk.5.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  50/ 291]               blk.5.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  51/ 291]             blk.5.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  52/ 291]                  blk.5.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  53/ 291]                  blk.5.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  54/ 291]                blk.5.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  55/ 291]                blk.5.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  56/ 291]                blk.5.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  57/ 291]                  blk.5.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  58/ 291]                  blk.6.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  59/ 291]               blk.6.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  60/ 291]             blk.6.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  61/ 291]                  blk.6.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  62/ 291]                  blk.6.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q6_K .. size =     8.00 MiB ->     3.28 MiB
[  63/ 291]                blk.6.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q6_K .. size =   112.00 MiB ->    45.94 MiB
[  64/ 291]                blk.6.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  65/ 291]                blk.6.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  66/ 291]                  blk.6.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  67/ 291]                  blk.7.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  68/ 291]               blk.7.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  69/ 291]             blk.7.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  70/ 291]                  blk.7.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  71/ 291]                  blk.7.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  72/ 291]                blk.7.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  73/ 291]                blk.7.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  74/ 291]                blk.7.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  75/ 291]                  blk.7.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  76/ 291]                  blk.8.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  77/ 291]               blk.8.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  78/ 291]             blk.8.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  79/ 291]                  blk.8.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  80/ 291]                  blk.8.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  81/ 291]                blk.8.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  82/ 291]                blk.8.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  83/ 291]                blk.8.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  84/ 291]                  blk.8.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  85/ 291]                  blk.9.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  86/ 291]               blk.9.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  87/ 291]             blk.9.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  88/ 291]                  blk.9.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  89/ 291]                  blk.9.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q6_K .. size =     8.00 MiB ->     3.28 MiB
[  90/ 291]                blk.9.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q6_K .. size =   112.00 MiB ->    45.94 MiB
[  91/ 291]                blk.9.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  92/ 291]                blk.9.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  93/ 291]                  blk.9.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[  94/ 291]                 blk.10.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  95/ 291]              blk.10.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[  96/ 291]            blk.10.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  97/ 291]                 blk.10.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[  98/ 291]                 blk.10.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[  99/ 291]               blk.10.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[ 100/ 291]               blk.10.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[ 101/ 291]               blk.10.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[ 102/ 291]                 blk.10.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[ 103/ 291]                 blk.11.attn_k.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[ 104/ 291]              blk.11.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[ 105/ 291]            blk.11.attn_output.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[ 106/ 291]                 blk.11.attn_q.weight - [ 4096,  4096,     1,     1], type =    f16, converting to q4_K .. size =    32.00 MiB ->     9.00 MiB
[ 107/ 291]                 blk.11.attn_v.weight - [ 4096,  1024,     1,     1], type =    f16, converting to q4_K .. size =     8.00 MiB ->     2.25 MiB
[ 108/ 291]               blk.11.ffn_down.weight - [14336,  4096,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[ 109/ 291]               blk.11.ffn_gate.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB
[ 110/ 291]               blk.11.ffn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MiB
[ 111/ 291]                 blk.11.ffn_up.weight - [ 4096, 14336,     1,     1], type =    f16, converting to q4_K .. size =   112.00 MiB ->    31.50 MiB

In [4]:
import os
from huggingface_hub import HfApi

if not os.path.exists("/content/custom-mistral-yt-seo-Q4_K_M.gguf"):
    print("❌ Wait! The 4GB file wasn't created. Check the logs above.")
else:
    print("✅ 4GB file found! Uploading to Hugging Face...")
    api = HfApi()
    try:
        api.upload_file(
            path_or_fileobj="/content/custom-mistral-yt-seo-Q4_K_M.gguf",
            path_in_repo="custom-mistral-yt-seo-Q4_K_M.gguf",
            repo_id="SujalChhajed925/yt-seo-mistral-merged",
            token="YOUR_HF_TOKEN" # <-- IMPORTANT: Put your token here!
        )
        print("\n🎉 UPLOAD COMPLETE! You can safely close Google Colab forever.")
    except Exception as e:
        print(f"\n❌ UPLOAD FAILED: {str(e)}")

✅ 4GB file found! Uploading to Hugging Face...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...istral-yt-seo-Q4_K_M.gguf:   0%|          |  531kB / 4.37GB

🎉 UPLOAD COMPLETE! You can safely close Google Colab forever.